#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-$(CONFIG_CAMERA_GC0301)		+= prize_dual_camera/
obj-$(CONFIG_PRIZE_FM)		+= fm_ant/
obj-$(CONFIG_PRIZE_AW2016A)		+= aw2016a/
obj-$(CONFIG_LEDS_AW210XX)		+= AW210XX/
obj-$(CONFIG_PRIZE_HARDWARE_INFO)		+= hardware_info/
obj-$(CONFIG_PRIZE_EXERGEN)		+= prize_exergen/
obj-$(CONFIG_PRIZE_DMR009)	+= dmr009/
#prize add by liuxuhui for modify send lcm param to light sensor
obj-$(CONFIG_PRIZE_PIXEL_MANAGER) += pixel_manager/
