#obj-m += smartpa.o
#smartpa-y += aw883xx.o aw_monitor.o aw_bin_parse.o aw_device.o aw_init.o aw_calib.o aw_spin.o

obj-m += smartpa.o
smartpa-y	+= aw883xx.o
smartpa-y	+= aw_monitor.o
smartpa-y	+= aw_bin_parse.o
smartpa-y	+= aw_device.o
smartpa-y	+= aw_init.o
smartpa-y	+= aw_calib.o
smartpa-y	+= aw_spin.o
