#semitouch touchpanel driver
ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(srctree)/drivers/gpu/drm/mediatek/mediatek_v2/
obj-m += chsc5xxx.o

chsc5xxx-objs += basic_util.o
chsc5xxx-objs += i2c_communication.o
chsc5xxx-objs += qual_core.o
chsc5xxx-objs += semi_touch_function.o
chsc5xxx-objs += semi_touch_upgrade.o
chsc5xxx-objs += semi_touch_apk.o
chsc5xxx-objs += semi_touch_device.o
chsc5xxx-objs += semi_touch_custom.o

